### ISSUE TITLE
Error while loading the game

### ISSUE THREAD

**Issue by sapphired18** [ManlyMarco/AI-HF_Patch#1]
[Warning: Unity Log] 読み込みエラー
assetBundleName：list/title.unity3d     assetName：title_map
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AIProject.TitleScene.LoadMapList () (at <ba0ba0a169ce40d193891969ec160dc1>:0)
AIProject.TitleScene+<Start>c__Iterator0.MoveNext () (at <ba0ba0a169ce40d193891969ec160dc1>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <0a7d89e4511e4bdeb215f76ca00fd04e>:0)

**Comment by ManlyMarco** [comment]
Are you trying to use it on the steam release? It's not yet compatible.

**Comment by sapphired18** [comment]
i crack it, from fitgirl

**Comment by ManlyMarco** [comment]
Sounds like it's the steam version of the game, which is currently not supported. Next release of hf patch will add support for it.
