### ISSUE TITLE
AI Shoujo version 1.0.0 fitgirl repack work with newest patch?

### ISSUE THREAD

**Issue by gabeixa** [ManlyMarco/AI-HF_Patch#11]
does the newest patch work for version 1.0.0 AI Shoujo fitgirl repack?

**Comment by ManlyMarco** [comment]
HF Patches work on all versions of the games they target unless the game files are damaged in some way.

**Comment by gabeixa** [comment]
> HF Patches work on all versions of the games they target unless the game files are damaged in some way.

thank you so much!
