### ISSUE TITLE
Torrent has no seeders - v2.11

### ISSUE THREAD

**Issue by DocNotVeryStrange** [ManlyMarco/AI-HF_Patch#13]
Any chance someone can seed the torrent for v2.11? I am unable to download it.
Would appreciate it a lot, thanks.

**Comment by ManlyMarco** [comment]
I can see a bunch of seeds, make sure it's not a problem with your connection or the torrent client.

**Comment by DocNotVeryStrange** [comment]
Yeah, I figured it out. It was like you said, my client was the problem. Reinstallation fixed the problem. Thanks though.
