### ISSUE TITLE
Game freezes at startup "[Debug  :IllusionFixes] Starting unused asset cleanup"

### ISSUE THREAD

**Issue by Actiol** [ManlyMarco/AI-HF_Patch#14]
The game & studio both freeze at startup with "[Debug  :IllusionFixes] Starting unused asset cleanup" being the last message in the console thus most likely being the cause for the freeze.
![console](https://user-images.githubusercontent.com/68166781/149572241-d9ecb7db-1858-4d13-bdc6-12b913f215e7.png)

**Comment by ManlyMarco** [comment]
Does the game start fine with all mods disabled? (Remove winhttp.dll from game directory)
The cleanup log message is about something that happens even in a game without mods so it's unlikely to cause a lockup.

**Comment by Actiol** [comment]
Oh yea. It doesn't start without mods. But the odd thing is that it worked until a couple of weeks ago. 
So unrelated to your work, do you know what could be the cause for this?

**Comment by ManlyMarco** [comment]
It could be anything really. Try rebooting and running the game as admin. If you have the game on Steam then try verifying local files (otherwise reinstall) and install the patch again. Check your drive for errors with chkdsk/smart, maybe it's choking itself to death.
