### ISSUE TITLE
Cooking doesn't work

### ISSUE THREAD

**Issue by denisrend** [ManlyMarco/AI-HF_Patch#15]
![image](https://user-images.githubusercontent.com/98656377/151668212-45193f8b-92a8-4e12-928d-23dab721d435.png)
When I try to cook food, there are no recipes on the menu.Everything works without a patch

**Comment by ManlyMarco** [comment]
Post your output_log.txt from game directory.

**Comment by denisrend** [comment]
[output_log.txt](https://github.com/ManlyMarco/AI-HF_Patch/files/7964894/output_log.txt)

**Comment by ManlyMarco** [comment]
Nothing wrong in the log, try asking on the discord server.

**Comment by denisrend** [comment]
Oh,I found a solution, you need to click on the pan in the upper left corner of the menu.
