### ISSUE TITLE
[Bug]Does not support high heels

### ISSUE THREAD

**Issue by yangluo0901** [ManlyMarco/AI-HF_Patch#18]
I have updated the patch to the latest version, but it does not support high heels, the high heels shoes sink into the ground. I tried to find the solution, but no luck, any help would be appreciated! Please let me know if you need further info to narrow down and solve the issue

**Comment by ManlyMarco** [comment]
Make sure that the Heelz plugin got installed. Otherwise, it's probably this issue https://github.com/hooh-hooah/IL_Heelz/issues/22

**Comment by yangluo0901** [comment]
Thank you for your reply. How do I check if the Heelz plugin is installed? I do have AI_Heelz.dll 1.14.3 in my plugin folder, I assume that means Heelz is installed. I also tried to downgrade it to the 1.13 and 1.12 version, but no luck. I bought the game from Steam, does Heelz support this version? I left a comment on [Heels sink into the ground #22](https://github.com/hooh-hooah/IL_Heelz/issues/22) but looks like it is not being maintained. Really appreciate it if there is any suggestion?

**Comment by ManlyMarco** [comment]
Try using the older version as mentioned in the issue.

**Comment by ManlyMarco** [comment]
Closing as stale, if the issue persists please open a new issue.
