### ISSUE TITLE
Steam - Characters stack ontop of each other after exiting from sex scene

### ISSUE THREAD

**Issue by Lu5ck** [ManlyMarco/AI-HF_Patch#2]
As topic :O

**Comment by ManlyMarco** [comment]
Try removing bepinex\plugins\heelz.dll

I've released an updated version of the patch with this plugin disabled when installing on to the Steam release. You don't have to redownload it, the only difference is removing the heelz.dll

**Comment by Lu5ck** [comment]
That fixed it.
