### ISSUE TITLE
LEgs acting weird with latest patch

### ISSUE THREAD

**Issue by Jaythulu** [ManlyMarco/AI-HF_Patch#20]
So a fews of days ago I did a complete reinstall with the latest patch (and fully updated), made a character and a couple of girls, and now any time I initiate a "missionary" or other non-doggy style pose, including cunnilingus (floor or desk), my characters legs flail around wildly like a bird flapping its wings. They pass through each other and through any character I'm interacting with (including shan). I've now tried both a regular male character and a futanari woman character (made using the default character that loads when opening the character creator), and slightly custom ones using a variety of bodies from the default to BP4, BP5 and SAC. The behaviour persists no matter what changes I make.

Specifically looks like it's the hip joints that're causing this behaviour, swinging the rest of the legs way too far out and way too far in. I tried using the "joint correction" and other bone/sex-related correction settings in the mod configuration options, but nothing changed. I definitely did not have this issue with patch 2.12.

Any idea how I can fix this?

**Comment by ManlyMarco** [comment]
It could be heelz, could be abmx, could be something crashing random parts of the game.

**Comment by ManlyMarco** [comment]
Closing as stale, if the issue persists please open a new issue.
