### ISSUE TITLE
胸部大小能调到超过100吗？

### ISSUE THREAD

**Issue by hqy662** [ManlyMarco/AI-HF_Patch#21]
Can you go over 100 breasts? By disassembly. Machine translation.

**Comment by ManlyMarco** [comment]
I assume you meant to ask if chest size be adjusted to more than 100.
For most sliders, you can type in much higher values in the input box and apply with the enter key. Some sliders don't allow this, I don't remember if this one allows it or not, you'll have to try it. You can also increase slider unlocker limits in plugin settings.

**Comment by hqy662** [comment]
> I assume you meant to ask if chest size be adjusted to more than 100. For most sliders, you can type in much higher values in the input box and apply with the enter key. Some sliders don't allow this, I don't remember if this one allows it or not, you'll have to try it. You can also increase slider unlocker limits in plugin settings.

It didn't work. What plug-in?

**Comment by ManlyMarco** [comment]
Slider Unlocker.
