### ISSUE TITLE
Issues with installer on wine  

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [ManlyMarco/AI-HF_Patch#22]
After following [the guide](https://github.com/Mantas-2155X/illusion-wine-guide/blob/master/parts/setup-wineprefix.md) mentioned in `README.md` I am experiencing issue with the installer.

After executing the installer file a window with language picker shows up. After selecting language I get this error:
![image](https://github.com/ManlyMarco/AI-HF_Patch/assets/29522138/381303db-cb19-410e-9cb6-41b808df611e)

I am not really knowledgeable when it comes to the management of `dotnet` runtimes in wine but I guess `winetricks` removes `wine-mono` when calling any verb that installs `dotnet`. I wonder what should I do. 

<details><summary>This is the output of wine (unset `WINEDEBUG` variable):</summary><br>
<pre><code>wineserver: using server-side synchronization.
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 8.10 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0110:fixme:thread:GetThreadUILanguage : stub, returning default language.
0110:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0062D97C, 00000000 0062D9A4
0110:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0062D97C 00000000 0062D9A4) returning a dummy value (current locale)
0110:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0062D97C, 0162A680 0062D9A4
0110:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0062D97C 0162A680 0062D9A4) returning a dummy value (current locale)
0118:fixme:thread:GetThreadUILanguage : stub, returning default language.
0118:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0084D9C8, 00000000 0084D9F0
0118:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0084D9C8 00000000 0084D9F0) returning a dummy value (current locale)
0118:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 0084D9C8, 018519B0 0084D9F0
0118:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 0084D9C8 018519B0 0084D9F0) returning a dummy value (current locale)
0118:fixme:wtsapi:WTSRegisterSessionNotification Stub 0001009E 0x00000000
0118:fixme:uxtheme:BufferedPaintInit Stub ()
0118:fixme:win:DisableProcessWindowsGhosting : stub
0118:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
0118:fixme:graphics:ShutdownBlockReasonCreate (0001009E, L"Installing"): stub
0118:fixme:msg:ChangeWindowMessageFilterEx 000100B2 c053 1 00000000
0118:fixme:msg:ChangeWindowMessageFilterEx 000200B2 c053 1 00000000
0118:fixme:rstrtmgr:RmStartSession 006D5768, 0, 006D576C stub!
0118:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0118:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 12013109, 28) stub
0118:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
0118:fixme:graphics:ShutdownBlockReasonCreate (0001009E, L"Installing HF Patch for AI-Syoujyo and AI-Shoujo."): stub
0118:fixme:msg:ChangeWindowMessageFilterEx 000300B2 c053 1 00000000
0118:fixme:msg:ChangeWindowMessageFilterEx 000400B2 c053 1 00000000
0118:fixme:msg:ChangeWindowMessageFilterEx 000200C2 c053 1 00000000
0118:fixme:msg:ChangeWindowMessageFilterEx 000300C2 c053 1 00000000
0118:fixme:shell:SHAutoComplete stub
0118:err:richedit:ReadStyleSheet skipping optional destination
0118:err:richedit:ReadStyleSheet skipping optional destination
0118:err:richedit:ReadStyleSheet skipping optional destination
0118:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 12F2060D, 28) stub
0118:fixme:heap:GetNumaHighestNodeNumber semi-stub: 0084F58C
0118:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 12F10000) stub
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 4 12B7674C 0084CD74 0084D3C8 00000000
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 12B8F960 0084CF64 0084D5B8 00000000
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 12B8F960 0084CF64 0084D5B8 00000000
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 12B80BEC 0084D8FC 0084DF50 00000000
0118:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 0084EF08 00000000 0084EF04) returning a dummy value (current locale)
0118:fixme:nls:get_dummy_preferred_ui_language (0x8 0x409 0084EF08 12B9B268 0084EF04) returning a dummy value (current locale)
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 12B9AB50 0084CBB4 0084D208 00000000
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 12B9AB50 0084CDA4 0084D3F8 00000000
0118:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 2 12B9AB50 0084CDA4 0084D3F8 00000000
0118:fixme:rstrtmgr:RmEndSession 3735928559 stub!
0118:fixme:graphics:ShutdownBlockReasonDestroy (0001009E): stub
0118:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0001009E
0118:fixme:uxtheme:BufferedPaintUnInit Stub ()
</code></pre>
</details> 

Info about my system:
- OS: Manjaro Linux x86_64
- Kernel: 6.4.0-1-MANJARO
- DE: Plasma 5.27.5
- `wine --version`: `wine-8.10.r5.geb5a19f4 ( TkG Staging Esync Fsync )`
- specific commands used:
  ```
  export WINEPREFIX=/some/path/to/prefix`
  winetricks corefonts dxvk ole32
  winetricks -q dotnet35
  winetricks -q dotnet472
  wine reg add "HKEY_CURRENT_USER\Software\Wine\DllOverrides" /v winhttp /t reg_sz /d native,builtin /f
  wine reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Avalon.Graphics" /v DisableHWAcceleration /t REG_DWORD /d 1 /f
  wine reg ADD 'HKEY_CURRENT_USER\Software\Wine\X11 Driver' /v UseTakeFocus /d 'N' /f
  wine 'AI-Shoujo HF Patch v2.15.exe'
  ```

It is worth mentioning that the installer works perfectly fine on clean prefix (without installing `dotnet35` and `dotnet472`).

**Comment by ManlyMarco** [comment]
I have no idea honestly, the installer is not written in .NET, it only loads a helper lib that uses .NET 4.6 partway through but you should get an error at the load time if it does fail, not at startup. The steps in the guide are tailored for the games and the game launchers so some steps might be different for the patches. I suggest asking the author of the guide.

**Comment by papaj-na-wrotkach** [comment]
Thank you for your reply, I will ask the author of the guide about it. I will post any solutions here if I somehow manage to get it to work.

**Comment by ManlyMarco** [comment]
You might have an easier time contacting him on either Koikatsu or IS discord server.

**Comment by papaj-na-wrotkach** [comment]
Thanks! I'll use your suggestion.

I found his Discord tag on patreon: `2155X#2917`. Discord removed discriminator system and there are two users with `2155X` in nickname on Koikatsu Discord server. Do you know which account he is using?
![image](https://github.com/ManlyMarco/AI-HF_Patch/assets/29522138/ae6e2f1e-d3a6-4c48-b084-eda500c8586a)

I guess it is the first one but I just want to make sure...

**Comment by ManlyMarco** [comment]
Yes the first one.
