### ISSUE TITLE
Has the version gone backwards?

### ISSUE THREAD

**Issue by hcllmsx** [ManlyMarco/AI-HF_Patch#24]
Before installing this patch, the version number of the game itself was v1.10. After installation, the bottom right corner became v1.01. Is that a step back? Will this have any impact?

安装这个补丁之前，游戏本体的版本号是v1.10，安装完成之后，右下角却成了v1.01，是倒退了吗？这会有什么影响吗？

**Comment by ManlyMarco** [comment]
If you have the game on Steam, then yes, it's changed into an older version to remove limitations added in updates. If you saved cards in the new version then the breast size and height sliders will be different and might need to be readjusted (they are limited to a smaller range in the latest version).
