### ISSUE TITLE
It's not a problem, it's a question!

### ISSUE THREAD

**Issue by kawaii910** [ManlyMarco/AI-HF_Patch#26]
.

**Comment by ManlyMarco** [comment]
Hello! There are no plans on any new content for this game since most people have long moved on to newer games. I've never tried playing with a non-male MC outside of brief test runs so I can't really help you. You can try asking on the discord server, link is in the game launcher.

**Comment by kawaii910** [comment]
Awww... I see... Thank you for your response!
