### ISSUE TITLE
I Can't put balls on Female Chara?

### ISSUE THREAD

**Issue by Elioraa** [ManlyMarco/AI-HF_Patch#3]
hey, since your mod allow me to choose the balls for female futa, i like to also put balls on my chara too, to make a trap chara. But the balls doesn't appear on my chara, is this normal? if not, then how do i suppose to fix this problem?

**Comment by ManlyMarco** [comment]
This sounds like an UncensorSelector issue, can you post this issue here so the author can look at it? https://github.com/DeathWeasel1337/KK_Plugins/issues

**Comment by Elioraa** [comment]
thanks dude
