### ISSUE TITLE
should i still use a vpn to install this patch,

### ISSUE THREAD

**Issue by NanoViridescence** [ManlyMarco/AI-HF_Patch#7]
i know you said it doesnt count as piracy but im afraid about the fact that i might get in trouble for just installing the patch

**Comment by ManlyMarco** [comment]
When installing the patch it doesn't connect to the internet so it doesn't matter. If you are worried about downloading the torrent, then it depends on your ISP. If your traffic is being monitored then it might be a good idea to use a VPN in general not just for this.
