### ISSUE TITLE
magnet: links are not working

### ISSUE THREAD

**Issue by lemmy04** [ManlyMarco/AI-HF_Patch#8]
magnet: links are not working, and downloading 13gig from patreon in one large http transfer's not likely to finish successfully.

**Comment by ManlyMarco** [comment]
The links are working, try a different torrent client like qBittorrent.

**Comment by lemmy04** [comment]
yup, qbittorrent works.

related question: I just installed the 2.3 version, and ran the built in updater - do i install 2.4 agaiin, or can i from now on just use the updater?

**Comment by ManlyMarco** [comment]
Updater only updates content mods, you need to install the new patch to update plugins and install any new game updates.

**Comment by lemmy04** [comment]
> 
> 
> Updater only updates content mods, you need to install the new patch to update plugins and install any new game updates.

ok, thanks, i better do that then...
