### ISSUE TITLE
problems with catching chickens in game - could this be related to the patch?

### ISSUE THREAD

**Issue by lemmy04** [ManlyMarco/AI-HF_Patch#9]
Hi,
whenever I catch a chicken in the game and try to put it in a chicken coop it just disappears - could this be related to one of the mods?

**Comment by ManlyMarco** [comment]
If you installed the patch and didn't change anything then it should work, there weren't any other reports of this being an issue.

Try asking in help channel on the discord server. These issues are mostly for problems with the patcher itself.
